[package]
name = "A Cold Cell"
description = "A quest mod for May Modathon 2023 - SSQN addon."
homepage = "https://www.nexusmods.com/morrowind/mods/52832"
repository = "https://github.com/tewlwolow/A-Cold-Cell"
authors = ["tewlwolow"]
version = "1.0.4"

[tools.mwse]
lua-mod = "tew.AColdCell"
wait-until-initialize = false

[dependencies]
assets = [
	"Icons\\tew\\acoldcell",
]

[dependencies.mods."A Cold Cell"]
plugin = "A Cold Cell.ESP"


[dependencies.mods."Skyrim Style Quest Notifications"]
mwse-module = "SSQN"
url = "https://www.nexusmods.com/morrowind/mods/53175"

[dependencies.mwse]
buildnumber = 3150

[dependencies.mge-xe]
version = ">=0.15.0"

